config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root 'pictures#index'
  resources :pictures

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture, optional: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to picture_path(comment_params[:picture_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :review, :picture_id)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  # before_filter :authorize

  before_action :set_picture, only: [:show, :edit, :update, :destroy]


  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @comment = Comment.new
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :pictures, notice: 'Account successfully created'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- <%= form.label :name %> -->
    <div class="comment-group">
      <%= form.text_field :name, id: :comment_name, placeholder: "Name" %>
    </div>
  </div>

  <div class="field">
    <!-- <%= form.label :review %> -->
    <div class="comment-group">
      <%= form.text_area :review, id: :comment_review, placeholder: "Add Comment" %>
    </div>
  </div>

  <div class="field">
    <%= form.hidden_field :picture_id, id: :comment_picture_id, value: @picture.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Review</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.review %></td>
        <td><%= comment.picture %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>
<%= link_to 'Back', pictures_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Review:</strong>
  <%= @comment.review %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @comment.picture.title %>
</p>

<!-- <%= link_to 'Edit', edit_comment_path(@comment) %> | -->
<%= link_to 'Home', pictures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Murall</title>
  <%= csrf_meta_tags %>

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Forum" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Grand+Hotel|Poiret+One" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/packery/2.1.1/packery.pkgd.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <header>
  <nav class="home-menu">
    <div class="right-nav">
      <% if current_user %>
      <div class="logged-user">
        <i class="fa fa-user-o" aria-hidden="true"></i> <%= current_user.name %> | <%= link_to "logout", '/logout' %>
      </div>

      <% else %>
      <div class="login-user">
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>


      </div>

      <% end %>
  </div>

  <div class="left-nav">
    <div class="streetart-icon">
      <%= link_to new_picture_path do %>
      <%= image_tag 'street-art2.png', alt: 'a face that is unnervingly happy'%>
      <% end %>
    </div>
  </div>
</nav>
</header>

  <%= yield %>
</body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<body class="back-ground">
  <div class="edit-info">
    <div class="comment-border">

        <h1>Edit Mural</h1>

        <%= render 'form', picture: @picture %>

        <%= link_to 'Back', @picture %> |
        <%= link_to 'Home', pictures_path %>
    </div>
  </div>
</body

app/views/pictures/index.html.erb
<body class="back-ground">
  <!-- <div class="entire">
    <div class="header">
      <div class="nav">
        <div class="text">
          <%= image_tag ( "logo.png") %>
        </div>
      </div>
    </div> -->
    <% unless current_user %>

    <div id="notice"><%= notice %></div>

    <div class="user-border">

      <h1 class="center">Login</h1>

      <%= form_tag '/login' do %>
      <div class="form-group">
        <%= text_field_tag :email, '', placeholder: "Email" %>
      </div>
      <div class="form-group">
        <%= password_field_tag :password, '', placeholder: "Password" %>
      </div>

      <center class="submit">
      <%= submit_tag "Submit" %>
    </center>
      <% end %>
    </div>
    <% else %>
    <div class="outer-div ">
      <div class="left-div grid">
        <% @pictures.each do |picture| %>
          <div class='grid-item' onclick='window.location.href = "<%= picture_path(picture) %>"'>

            <%= image_tag(picture.url, class: "image-view") %>
            <div class="title"><%= picture.title %></div>
          </div>
        <% end %>
      </div>
    </div>
    <br>

    <div class="upload">
      <%= link_to new_picture_path do %>
      <i class="fa fa-plus-square-o" aria-hidden="true"></i>

      <% end %>
    </div>


<% end %>
  </div>
</body>

app/views/pictures/new.html.erb
<body class="back-ground">
<!-- <div class="entire">
  <div class="header">
    <div class="nav">
      <div class="text">
        <%= image_tag ( "logo.png") %>
      </div>
    </div>
  </div> -->


<div class="new-info">

  <div class="comment-border">


    <h1>New Mural</h1>

    <%= render 'form', picture: @picture %>

    <%= link_to 'Back', pictures_path %>

  </div>

</div>

</body>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<body class="show_main">

  <div class="image">
      <%= image_tag @picture.url %>
    </div>
    <!-- <div class="artist">
      <a href="https://www.instagram.com/alexis_diaz/?hl=en" target='_blank'>@Alexis Diaz</a>
    </div>
  </div> -->

  <div class="pic-info">

    <h3 class="title">
      <!-- <strong>Title:</strong> -->
      <%= @picture.title %>
    </h3>

    <%= link_to 'Edit', edit_picture_path(@picture) %> |
    <%= link_to 'Delete', @picture, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <br>
    <div class="comment-border">

      <%= render 'comments/form', comment: @comment %>

      <h4 class="commtitle">Comments</h4>

      <% @picture.comments.each do |comment| %>
        <p>
          <u><strong>@<%= comment.name %></strong></u> :
          <%= comment.review %>
          <br>
          <div class="time-font">Added <%= time_ago_in_words comment.created_at %> ago</div>
        </p>
      <% end %>

    </div>
    <br>
    <%= link_to 'Home', pictures_path %>
  </div>

</body>

app/views/users/new.html.erb
<body class="back-ground">
  <!-- <div class="entire">
    <div class="header">
      <div class="nav">
        <div class="text">
          <%= image_tag ( "logo.png") %>
        </div>
      </div>
    </div> -->


    <div class="user-border">
      <h1 class="center">Signup!</h1>

      <%= form_for :user, url: '/users' do |f| %>
<div class="form-group">
  <%= f.text_field :name, placeholder: "Name" %>
</div>
<div class="form-group">
  <%= f.text_field :email, placeholder: "Enter your Email" %>
</div>

<div class="form-group">
  <%= f.password_field :password, placeholder: "Password" %>
</div>
<div class="form-group">
  <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
</div>
       <center class="submit">
      <%= f.submit "Submit" %></center>

      <% end %>
    </div>
</body>